### ISSUE TITLE
Play Services GcmTaskService NPE in onStartCommand

### ISSUE THREAD

**Issue by gitkobold** [google/gcm#131]
Version: 8.1.0
I don't use/override the onStartCommand.

1   at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2891)
2   at android.app.ActivityThread.access$2400(ActivityThread.java:141)
3   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
4   at android.os.Handler.dispatchMessage(Handler.java:102)
5   at android.os.Looper.loop(Looper.java:136)
6   at android.app.ActivityThread.main(ActivityThread.java:5333)
7   at java.lang.reflect.Method.invokeNative(Native Method)
8   at java.lang.reflect.Method.invoke(Method.java:515)
9   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
10  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
11  at dalvik.system.NativeStart.main(Native Method)
12Caused by: java.lang.NullPointerException
13  at com.google.android.gms.gcm.GcmTaskService.onStartCommand(Unknown Source)
14  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2854)
15  ... 10 more

**Comment by weitzj** [comment]
I got the same bug for some devices in this line from `onStartCommand` of the `GcmTaskService`

```
if("com.google.android.gms.gcm.ACTION_TASK_READY".equals(intent.getAction()))
```

`intent` is `null`

**Comment by gitkobold** [comment]
I don't overwrite onStartCommand yet... 
What should we do with this? Overwrite it and stop the service if intent is null, or ...?
What would solve this bug?

**Comment by henrik-lindqvist** [comment]
Dup: https://github.com/google/gcm/issues/87
