### ISSUE TITLE
WakeLock under-locked GCM_LIB issue.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gcm#19]
```
My app uses gcm-android library r3 and
I've got a few error reports about this error.

java.lang.RuntimeException: WakeLock under-locked GCM_LIB
at android.os.PowerManager$WakeLock.release(PowerManager.java:325)
at android.os.PowerManager$WakeLock.release(PowerManager.java:300)
at 
com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.
java:252)

I used same way as sample and when I saw the gcm source this couldn't happen, 
but... it seems it does.

Am I using it wrong or is it gcm but?
```

Original issue reported on code.google.com by `noranb...@gmail.com` on 31 Mar 2013 at 8:54

**Comment by silvolu** [comment]
This has been fixed in the [new version of the API](https://developers.google.com/android/reference/com/google/android/gms/gcm/GcmListenerService).
