### ISSUE TITLE
send() throws NPE if payload has data with null value

### ISSUE THREAD

**Issue by tjohns** [google/gcm#5]
Original [issue 5](https://code.google.com/p/gcm/issues/detail?id=5) created by google on 2012-08-01T20:13:57.000Z:

Here's the stack trace:

java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:205)
	at com.google.android.gcm.server.Sender.sendNoRetry(Sender.java:166)
	at com.google.android.gcm.server.Sender.send(Sender.java:121)

Sender should either check if the value is null, or Message's addData() should not allow it...

**Comment by tjohns** [comment]
Comment [#1](https://code.google.com/p/gcm/issues/detail?id=5#c1) originally posted by google on 2012-08-22T20:50:00.000Z:

Fixed by http://code.google.com/p/gcm/source/detail?r=72132950b9ea ; will be available on next release.
