### ISSUE TITLE
ANR keyDispatchingTimedOut

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gcm#53]
```
----- pid 1530 at 2015-02-08 21:48:49 -----
Cmd line: [app package]

JNI: CheckJNI is off; workarounds are off; pins=7; globals=223

DALVIK THREADS:
(mutexes: tll=0 tsl=0 tscl=0 ghl=0)

"main" prio=5 tid=1 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40e31a18 self=0x40e21840
| sysTid=1530 nice=0 sched=0/0 cgrp=apps handle=1074559068
| state=S schedstat=( 77522793240 23275637577 91928 ) utm=6819 stm=933 core=0
#00 pc 00021d9c /system/lib/libc.so (__futex_syscall3+8)
#01 pc 0000e468 /system/lib/libc.so (__pthread_cond_timedwait_relative+48)
#02 pc 0000e4c4 /system/lib/libc.so (__pthread_cond_timedwait+60)
#03 pc 0005452d /system/lib/libdvm.so (dvmChangeStatus(Thread*, 
ThreadStatus)+72)
#04 pc 0004e2e5 /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, 
JValue*, Method const*, Thread*)+508)
#05 pc 00027ba0 /system/lib/libdvm.so
#06 pc 0002bd74 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, 
JValue*)+180)
#07 pc 000618d3 /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, 
ArrayObject*, ArrayObject*, ClassObject*, bool)+374)
#08 pc 00069879 /system/lib/libdvm.so
#09 pc 00027ba0 /system/lib/libdvm.so
#10 pc 0002bd74 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, 
JValue*)+180)
#11 pc 000615ad /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, 
Object*, bool, JValue*, std::__va_list)+272)
#12 pc 0004a5b5 /system/lib/libdvm.so
#13 pc 0004ff49 /system/lib/libandroid_runtime.so
#14 pc 00050d71 /system/lib/libandroid_runtime.so 
(android::AndroidRuntime::start(char const*, char const*)+400)
#15 pc 00000db7 /system/bin/app_process
#16 pc 0001c354 /system/lib/libc.so (__libc_init+64)
#17 pc 00000ae8 /system/bin/app_process
at android.os.BinderProxy.transact(Native Method)
at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:279)
at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:732)
at android.os.PowerManager$WakeLock.acquire(PowerManager.java:701)
at 
com.google.android.gcm.GCMBaseIntentService.runIntentInService(GCMBaseIntentServ
ice.java:278)
at 
com.google.android.gcm.GCMBroadcastReceiver.onReceive(GCMBroadcastReceiver.java:
52)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2550)
at android.app.ActivityThread.access$1500(ActivityThread.java:162)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5371)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)

NATIVE THREADS:
"m.stm.classlife" sysTid=1583 nice=0 sched=0/0 cgrp=apps
| state=S schedstat=( 185232 138771846 15 ) utm=0 stm=0 core=0

"m.stm.classlife" sysTid=1584 nice=0 sched=0/0 cgrp=apps
| state=S schedstat=( 618470920 871549886 7188 ) utm=27 stm=34 core=0

"m.stm.classlife" sysTid=1586 nice=0 sched=0/0 cgrp=apps
| state=S schedstat=( 655274616 957799001 6993 ) utm=18 stm=47 core=0

"m.stm.classlife" sysTid=1587 nice=0 sched=0/0 cgrp=apps
| state=S schedstat=( 291913911 3777213223 5016 ) utm=17 stm=12 core=0

----- end 1530 -----


```

Original issue reported on code.google.com by `Mr.boy...@gmail.com` on 17 Feb 2015 at 8:52

**Comment by silvolu** [comment]
The version of the library you're using is deprecated, please use the [latest version](https://developers.google.com/cloud-messaging)
