### ISSUE TITLE
java.lang.IllegalArgumentException: argument cannot be null in Sender.java when handling HTTP errors on multi-cast messages

### ISSUE THREAD

**Issue by tjohns** [google/gcm#7]
Original [issue 7](https://code.google.com/p/gcm/issues/detail?id=7) created by google on 2012-08-14T18:55:08.000Z:

<b>What steps will reproduce the problem?</b>

1. From the application server using the supplied gcm-server.jar helper classes, attempt to send a multicast message to the GCM server using API parameters that would result in the GCM replying with a non-200 HTTP status (Eg. 401 for error authenticating the sender account) 

<b>What is the expected output? What do you see instead?</b>

The expected result is for the Sender to throw a InvalidRequestException similar to how it does for non-multi cast messages. This would allow the user of the class to handle the  problem accordingly.

Instead, using the attached test case, the send request fails with:

Exception in thread &quot;main&quot; java.lang.IllegalArgumentException: argument cannot be null
	at com.google.android.gcm.server.Sender.nonNull(Sender.java:553)
	at com.google.android.gcm.server.Sender.getString(Sender.java:534)
	at com.google.android.gcm.server.Sender.sendNoRetry(Sender.java:365)
	at com.google.android.gcm.server.Sender.send(Sender.java:261)

<b>What version of the product are you using? On what operating system?</b>

The gcm-server.jar MANIFEST.MF file indicates:

Manifest-Version: 1.0
Ant-Version: Apache Ant 1.8.2
Created-By: 1.6.0-google-v4-61258-31622288 (Sun Microsystems Inc.)
Implementation-Vendor: Google
Implementation-Title: Google Cloud Messaging - server support
Implementation-Version: 1.0.2

This has been tested under Linux on two machines (same result): Ubuntu 10.04 LTS with java 1.6.0_26 and CentOS release 5.8 with 1.6.0_20.

<b>Please provide any additional information below.</b>

The original stackoverflow entry can be found here: http://stackoverflow.com/questions/11878428/exception-on-web-server-while-implementing-google-cloud-messaging/11944282#&nbsp;11944282

gcm group entry:
https://groups.google.com/forum/#!topic/android-gcm/VZhq7-QdLkA%5B1-25%5D

Attached is a test class which reproduces the problem.

**Comment by tjohns** [comment]
Comment [#1](https://code.google.com/p/gcm/issues/detail?id=7#c1) originally posted by google on 2012-08-22T20:49:18.000Z:

Fixed by http://code.google.com/p/gcm/source/detail?r=e8fda106f8c6 ; will be available on next release.

**Comment by tjohns** [comment]
Comment [#2](https://code.google.com/p/gcm/issues/detail?id=7#c2) originally posted by google on 2013-07-05T14:56:45.000Z:

Hi, I am getting this error because conn.getErrorStream() is returning null. The changes you made to Sender do not address this error, as getString() is still called the same way in getAndClose(). See http://stackoverflow.com/a/17491468/1596587

Thanks!

**Comment by tjohns** [comment]
Comment [#3](https://code.google.com/p/gcm/issues/detail?id=7#c3) originally posted by google on 2014-10-29T11:41:16.000Z:

I can reproduce this problem when using wrong GCM key.
