### ISSUE TITLE
Play Services GcmTaskService NPE in onStartCommand

### ISSUE THREAD

**Issue by niqo01** [google/gcm#87]
Android Play Services GcmTaskService doesn't check for null intent in onStartCommand which can happen.

GCM verison: 'com.google.android.gms:play-services-gcm:7.5.0'

```
java.lang.RuntimeException: Unable to start service com.couchsurfing.mobile.service.UploadAnalyticsService@1bd7c0cb with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2913)
       at android.app.ActivityThread.access$2100(ActivityThread.java:148)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1390)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5312)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
       at com.google.android.gms.gcm.GcmTaskService.onStartCommand()
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2896)
       at android.app.ActivityThread.access$2100(ActivityThread.java:148)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1390)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5312)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

Crashlytics: http://crashes.to/s/444c94037e4

**Comment by g-kjiang** [comment]
If the service was killed by the framework due to memory pressure, it will receive a null intent when the framework tries to bring it up again and tell it to continue doing whatever it was doing. 

Just wondering, did you override the onStartCommand() method and return START_STICKY by any chance? By default, GcmTaskService.onStartCommand() returns START_NOT_STICKY to avoid this situation.

**Comment by henrik-lindqvist** [comment]
The onStartCommand() is final so it can't be overridden to work around this issue.

If any Google employee reads this. Please don't make methods final, the APIs you provide will often contain bugs, doing this will prevent us developers from working around them!

EDIT: Misses this was specific for the GcmTaskService, i'am referring to the GcmListenerService.onStartCommand(), it will also throw NPE.

**Comment by g-kjiang** [comment]
Which onStartCommand() are you talking about? Did you mean the one in GcmTaskService? This one is not final.

**Comment by henrik-lindqvist** [comment]
GcmListenerService will also have this issue.

Sorry missed it was the specific to the GcmTaskService.

**Comment by morepork** [comment]
Do you have a specific example or stack trace from the GcmListenerService throwing a NPE in onStartCommand?

The method is deliberately marked final to avoid developers introducing bugs by changing underlying assumptions of the class.

**Comment by niqo01** [comment]
Here is how I solved the issue

```
  @Override
  public int onStartCommand(Intent intent, int flags, int startId) {
    if (intent == null) {
      // GcmTaskService doesn't check for null intent :(
      Timber.w("Invalid GcmTask null intent.");
      stopSelf();
      return START_NOT_STICKY;
    }
    return super.onStartCommand(intent, flags, startId);
  }
```

**Comment by henrik-lindqvist** [comment]
Sorry no stack trace, i looked at the decompiled GcmListenerService and it seems to call intent.getAction() without prior not-null check.

Not being able to "change underlying assumptions of the class" is of less importance when bugs are present in the final method. It makes it impossible to work around the issues, as demonstrated in the @niqo01 comment.

**Comment by dral3x** [comment]
@morepork I have a stacktrace regarding `GcmListenerService`

```
Package: com.spreaker.android
Version Code: 1013
Version Name: 4.0.1
Android: 5.1.1
Manufacturer: samsung
Model: SM-N920V
Date: Wed Nov 11 18:00:17 EST 2015

java.lang.RuntimeException: Unable to start service com.spreaker.android.radio.gcm.GcmReceiverService@11fc3c8f with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3972)
    at android.app.ActivityThread.access$2300(ActivityThread.java:197)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6897)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
    at com.google.android.gms.gcm.GcmListenerService.onStartCommand(Unknown Source)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3955)
    ... 9 more
```

Our `GcmReceiverService` extends `GcmListenerService` just to implements `onMessageReceived` method.

We're using the latest play services library (8.3.0) from `build.gradle`
`compile "com.google.android.gms:play-services-gcm:8.3.0"`

Hope this can help fix this issue.

**Comment by weitzj** [comment]
```
java.lang.RuntimeException: Unable to start service de.iosphere.st.snowreport.service.TaskSchedulerService@d831f1 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3276)
    at android.app.ActivityThread.access$2200(ActivityThread.java:172)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1520)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5832)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
    at com.google.android.gms.gcm.GcmTaskService.onStartCommand(Unknown Source)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3259)
    ... 9 more
```

**Comment by aitorvs** [comment]
I have another stack trace for this bug

```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.aitorvs.android.rsspace.service.FeedTaskService@4bc735e with null: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Intent.setExtrasClassLoader(java.lang.ClassLoader)' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
       at android.app.ActivityThread.access$2100(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Intent.setExtrasClassLoader(java.lang.ClassLoader)' on a null object reference
       at com.google.android.gms.gcm.GcmTaskService.onStartCommand(Unknown Source)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
       at android.app.ActivityThread.access$2100(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I am using GPS 8.4.0. If I were to override `onStartCommand()` to check for null intent, what's the int value expected to be returned?

**Comment by ogeidix** [comment]
This has been fixed in the next release of the library.
Meantime you can override it and return Service.START_NOT_STICKY is the input intent is null.

**Comment by divyenduz** [comment]
@ogeidix : Can you notify what version would that be ? Thanks

**Comment by ogeidix** [comment]
It will be in the next release of the library.
Unfortunately I don't know which version number will be used until the release team publishes it.

**Comment by divyenduz** [comment]
Sure, Thanks :)

**Comment by aitorvs** [comment]
@ogeidix Thanks!

**Comment by coliovacruz** [comment]
# Obrigado niqo01 isso resolveu minha vida!!!!

Here is how I solved the issue

  @Override
  public int onStartCommand(Intent intent, int flags, int startId) {
    if (intent == null) {
      // GcmTaskService doesn't check for null intent :(
      Timber.w("Invalid GcmTask null intent.");
      stopSelf();
      return START_NOT_STICKY;
    }
    return super.onStartCommand(intent, flags, startId);
  }
   ==============================
